name: acestus-dev-usw2

on:
  workflow_dispatch: 
  push:
    paths:
      - 'acestus-dev-usw2/**'

env:
  Location: 'westus2'
  Subscription: 'Acestus'
  StackName: 'stack-acestus-dev-usw2'
  ResourceGroup: 'rg-acestus-dev-usw2'
  TemplateFile: 'acestus-dev-usw2/acestus-dev-usw2.bicep'
  ParameterFile: 'acestus-dev-usw2/acestus-dev-usw2.bicepparam'

# don't touch below this line

jobs:
  update-bicep:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Ensure Resource Group Exists
      uses: azure/cli@v2
      with:
          azcliversion: '2.45.0'
          inlineScript: |
            az account set --subscription '${{ env.Subscription }}'
            if ! az group show --name '${{ env.ResourceGroup }}' &> /dev/null; then
              az group create --name '${{ env.ResourceGroup }}' --location '${{ env.Location }}'
            fi
      
    - name: Update Bicep file
      uses: azure/cli@v2
      with:
          azcliversion: latest
          inlineScript: |
            az stack group create --name '${{ env.StackName }}' --resource-group '${{ env.ResourceGroup }}' --template-file '${{ env.TemplateFile }}' --parameters '${{ env.ParameterFile }}' --deny-settings-mode 'none' --action-on-unmanage 'deleteResources' --yes