name: wweeks-lab-usw2

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - 'wweeks-lab-usw2/**'

env:
  Location: 'westus2'
  StackName: 'stack-wweeks-lab-usw2'
  ResourceGroup: 'rg-wweeks-lab-usw2'
  TemplateFile: 'wweeks-lab-usw2/wweeks-lab-usw2.bicep'
  ParameterFile: 'wweeks-lab-usw2/wweeks-lab-usw2.bicepparam'

jobs:
  update-bicep:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure Resource Group Exists
      uses: azure/cli@v2
      with:
          azcliversion: '2.45.0'
          inlineScript: |
            if ! az group show --name '${{ env.ResourceGroup }}' &> /dev/null; then
              az group create --name '${{ env.ResourceGroup }}' --location '${{ env.Location }}'
            fi
      
    - name: Update Bicep file
      uses: azure/cli@v2
      with:
          azcliversion: latest
          inlineScript: |
            az stack group create --name '${{ env.StackName }}' --resource-group '${{ env.ResourceGroup }}' --template-file '${{ env.TemplateFile }}' --parameters '${{ env.ParameterFile }}' --deny-settings-mode 'none' --action-on-unmanage 'deleteResources' --yes